# -*- coding: utf-8 -*-
# Licensed under the GPLv3
# 本项目由@Everyb0dyLies开发维护，使用python3

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowTitle("liarcom")
        MainWindow.resize(260, 330)
        MainWindow.setWindowFlags(QtCore.Qt.WindowCloseButtonHint)
        MainWindow.setFixedSize(MainWindow.width(), MainWindow.height())
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)

        self.topVerticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.topVerticalLayoutWidget.setObjectName("topVerticalLayoutWidget")
        self.topVerticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 260, 330))
        self.topVerticalLayout = QtWidgets.QVBoxLayout(self.topVerticalLayoutWidget)
        self.topVerticalLayout.setObjectName("topVerticalLayout")
        self.topVerticalLayout.setContentsMargins(0, 0, 0, 0)
        
        self.topLabel = QtWidgets.QLabel(self.topVerticalLayoutWidget)
        self.topLabel.setObjectName("topLabel")
        self.topLabel.setText("liarcom")
        self.topLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.topVerticalLayout.addWidget(self.topLabel)
        self.line0 = QtWidgets.QFrame(self.topVerticalLayoutWidget)
        self.line0.setObjectName("line0")
        self.line0.setFrameShape(QtWidgets.QFrame.HLine)
        self.line0.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.topVerticalLayout.addWidget(self.line0)
        self.gridLayout0 = QtWidgets.QGridLayout()
        self.gridLayout0.setObjectName("gridLayout0")
        self.topVerticalLayout.addLayout(self.gridLayout0)
        self.gridLayout1 = QtWidgets.QGridLayout()
        self.gridLayout1.setObjectName("gridLayout1")
        self.topVerticalLayout.addLayout(self.gridLayout1)
        self.line1 = QtWidgets.QFrame(self.topVerticalLayoutWidget)
        self.line1.setObjectName("line1")
        self.line1.setFrameShape(QtWidgets.QFrame.HLine)
        self.line1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.topVerticalLayout.addWidget(self.line1)
        self.logTextBrowser = QtWidgets.QTextBrowser(self.topVerticalLayoutWidget)
        self.logTextBrowser.setObjectName("logTextBrowser")
        self.logTextBrowser.setLineWrapMode(QtWidgets.QTextBrowser.NoWrap)
        self.topVerticalLayout.addWidget(self.logTextBrowser)

        spacerItem0 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout0.addItem(spacerItem0, 0, 0, 2, 1)
        self.userNameLabel = QtWidgets.QLabel(self.topVerticalLayoutWidget)
        self.userNameLabel.setObjectName("userNameLabel")
        self.userNameLabel.setText("学号：")
        self.gridLayout0.addWidget(self.userNameLabel, 0, 1, 1, 1)
        self.userNameLineEdit = QtWidgets.QLineEdit(self.topVerticalLayoutWidget)
        self.userNameLineEdit.setObjectName("userNameLineEdit")
        self.gridLayout0.addWidget(self.userNameLineEdit, 0, 2, 1, 1)
        self.passwordLabel = QtWidgets.QLabel(self.topVerticalLayoutWidget)
        self.passwordLabel.setObjectName("passwordLabel")
        self.passwordLabel.setText("密码：")
        self.gridLayout0.addWidget(self.passwordLabel, 1, 1, 1, 1)
        self.passwordLineEdit = QtWidgets.QLineEdit(self.topVerticalLayoutWidget)
        self.passwordLineEdit.setObjectName("passwordLineEdit")
        self.passwordLineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.gridLayout0.addWidget(self.passwordLineEdit, 1, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout0.addItem(spacerItem1, 0, 3, 2, 1)
        
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout1.addItem(spacerItem2, 0, 1, 1, 1)
        self.retryCheckBox = QtWidgets.QCheckBox(self.topVerticalLayoutWidget)
        self.retryCheckBox.setObjectName("retryCheckBox")
        self.retryCheckBox.setText("断线重连")
        self.gridLayout1.addWidget(self.retryCheckBox, 0, 2, 1, 1)
        self.retryTimesLabel = QtWidgets.QLabel(self.topVerticalLayoutWidget)
        self.retryTimesLabel.setObjectName("retryTimesLabel")
        self.retryTimesLabel.setText("重试次数")
        self.gridLayout1.addWidget(self.retryTimesLabel, 0, 3, 1, 1)
        self.retryTimesSpinBox = QtWidgets.QSpinBox(self.topVerticalLayoutWidget)
        self.retryTimesSpinBox.setObjectName("retryTimesSpinBox")
        self.gridLayout1.addWidget(self.retryTimesSpinBox, 0, 4, 1, 1)
        self.label0 = QtWidgets.QLabel(self.topVerticalLayoutWidget)
        self.label0.setObjectName("label0")
        self.label0.setText("次")
        self.gridLayout1.addWidget(self.label0, 0, 5, 1, 1)
        self.timeoutLabel = QtWidgets.QLabel(self.topVerticalLayoutWidget)
        self.timeoutLabel.setObjectName("timeoutLabel")
        self.timeoutLabel.setText("超时时间")
        self.gridLayout1.addWidget(self.timeoutLabel, 1, 3, 1, 1)
        self.timeoutSpinBox = QtWidgets.QSpinBox(self.topVerticalLayoutWidget)
        self.timeoutSpinBox.setObjectName("timeoutSpinBox")
        self.timeoutSpinBox.setMinimum(1)
        self.timeoutSpinBox.setMaximum(60*1)
        self.gridLayout1.addWidget(self.timeoutSpinBox, 1, 4, 1, 1)
        self.label1 = QtWidgets.QLabel(self.topVerticalLayoutWidget)
        self.label1.setObjectName("label1")
        self.label1.setText("m")
        self.gridLayout1.addWidget(self.label1, 1, 5, 1, 1)
        self.remPasswdCheckBox = QtWidgets.QCheckBox(self.topVerticalLayoutWidget)
        self.remPasswdCheckBox.setObjectName("remPasswdCheckBox")
        self.remPasswdCheckBox.setText("记住密码")
        self.gridLayout1.addWidget(self.remPasswdCheckBox, 1, 2, 1, 1)
        self.loginButton = QtWidgets.QPushButton(self.topVerticalLayoutWidget)
        self.loginButton.setObjectName("loginButton")
        self.gridLayout1.addWidget(self.loginButton, 2, 2, 1, 4)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout1.addItem(spacerItem3, 0, 6, 1, 1)

        QtCore.QMetaObject.connectSlotsByName(MainWindow)


class MainWindow(QtWidgets.QMainWindow, Ui_MainWindow):
    def __init__(self, controller, parent=None):
        super(MainWindow, self).__init__(parent)
        self.setupUi(self)

        self._controller = controller

