# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/ubuntu/Desktop/liarcom.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(261, 317)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 261, 316))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.topLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.topLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.topLabel.setObjectName("topLabel")
        self.verticalLayout.addWidget(self.topLabel)
        self.line0 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line0.setFrameShape(QtWidgets.QFrame.HLine)
        self.line0.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line0.setObjectName("line0")
        self.verticalLayout.addWidget(self.line0)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.passwordLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.passwordLabel.setObjectName("passwordLabel")
        self.gridLayout.addWidget(self.passwordLabel, 1, 1, 1, 1)
        self.userNameLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.userNameLineEdit.setObjectName("userNameLineEdit")
        self.gridLayout.addWidget(self.userNameLineEdit, 0, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 0, 2, 1)
        self.userNameLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.userNameLabel.setObjectName("userNameLabel")
        self.gridLayout.addWidget(self.userNameLabel, 0, 1, 1, 1)
        self.passwordLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.passwordLineEdit.setObjectName("passwordLineEdit")
        self.gridLayout.addWidget(self.passwordLineEdit, 1, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 3, 2, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 0, 1, 1, 1)
        self.retryTimesSpinBox = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.retryTimesSpinBox.setObjectName("retryTimesSpinBox")
        self.gridLayout_2.addWidget(self.retryTimesSpinBox, 0, 4, 1, 1)
        self.label1 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label1.setObjectName("label1")
        self.gridLayout_2.addWidget(self.label1, 1, 5, 1, 1)
        self.timeoutSpinBox = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.timeoutSpinBox.setObjectName("timeoutSpinBox")
        self.gridLayout_2.addWidget(self.timeoutSpinBox, 1, 4, 1, 1)
        self.retryCheckBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.retryCheckBox.setObjectName("retryCheckBox")
        self.gridLayout_2.addWidget(self.retryCheckBox, 0, 2, 1, 1)
        self.timeoutLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.timeoutLabel.setObjectName("timeoutLabel")
        self.gridLayout_2.addWidget(self.timeoutLabel, 1, 3, 1, 1)
        self.retryTimesLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.retryTimesLabel.setObjectName("retryTimesLabel")
        self.gridLayout_2.addWidget(self.retryTimesLabel, 0, 3, 1, 1)
        self.label0 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label0.setObjectName("label0")
        self.gridLayout_2.addWidget(self.label0, 0, 5, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 0, 6, 1, 1)
        self.remPasswdCheckBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.remPasswdCheckBox.setObjectName("remPasswdCheckBox")
        self.gridLayout_2.addWidget(self.remPasswdCheckBox, 1, 2, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 2, 2, 1, 4)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.line = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.logTextBrowser = QtWidgets.QTextBrowser(self.verticalLayoutWidget)
        self.logTextBrowser.setObjectName("logTextBrowser")
        self.verticalLayout.addWidget(self.logTextBrowser)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "liarcom"))
        self.topLabel.setText(_translate("MainWindow", "liarcom"))
        self.passwordLabel.setText(_translate("MainWindow", "密码："))
        self.userNameLabel.setText(_translate("MainWindow", "学号："))
        self.label1.setText(_translate("MainWindow", "m"))
        self.retryCheckBox.setText(_translate("MainWindow", "断线重连"))
        self.timeoutLabel.setText(_translate("MainWindow", "超时时间"))
        self.retryTimesLabel.setText(_translate("MainWindow", "重试次数"))
        self.label0.setText(_translate("MainWindow", "次"))
        self.remPasswdCheckBox.setText(_translate("MainWindow", "记住密码"))
        self.pushButton.setText(_translate("MainWindow", "登录"))

